### ISSUE TITLE
reorient/demux mixed-orientation reads

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-cutadapt#11]
**Current Behavior**
- reads are in mixed orientation (both R1 and R2 reads contain forward/reverse reads)
- reads also often contain barcodes
- reads also probably contain primers

Sounds like this is the output produced by at least one company, so may want to provide support for this.

**Proposed Behavior**
1. add method to demux "mixed orientation" read format in one step
2. add a method to reorient reads (I think this may make more sense to allow a modular pipeline of import as paired-end --> reorient reads --> extract barcodes --> trim primers)

**References**
[raised on forum](https://forum.qiime2.org/t/problem-with-demux/2402?u=nicholas_bokulich)

**Comment by jairideout** [comment]
[forum x-ref](https://forum.qiime2.org/t/importing-format-with-multiplexed-fastq-format-single-read-iwth-barcode-data-in-the-reads-both-forward-and-reverse-directions/2499?u=jairideout)

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/same-classifier-same-otu-different-sequencing-run-different-classification/3975/39)

**Comment by colinbrislawn** [comment]
[forum xref](https://forum.qiime2.org/t/mixed-oriented-reads/6242/)

**Comment by thermokarst** [comment]
A cutadapt protocol is outlined here:

https://cutadapt.readthedocs.io/en/stable/guide.html?highlight=orientation#demultiplexing-paired-end-reads-in-mixed-orientation

**Comment by Oddant1** [comment]
It looks like we've decided on something resembling @nbokulich's possible solution 1 where the reorientation and the demuxing are done together in the same step. This decision is based on the behavior described in the link to the `cutadapt` documentation @thermokarst linked above. We've come up with a couple possible ways of implementing this.
1. Add a `--reorient` flag to the existing `demux_paired` command that, when provided, would demux the user's reads as normal, then reorient them and demux again
2. Create a new `demux_paired_reorient` that would implement the behavior described above in its own entirely separate method
Making this the default behavior feels excessive as it could significantly slow down the demuxing process. @thermokarst and I also discussed the possible issue of how to let the user know this is something they might want to do i.e. how do they know if their data is formatted in a manner that would require this? Any thoughts or comments on any of the above are appreciated.

**Comment by thermokarst** [comment]
I think I am leaning more towards a param on the existing `demux_paired` method --- maybe `mixed_orientation: bool = False`?

**Comment by Oddant1** [comment]
@thermokarst I think I prefer that idea too

**Comment by Oddant1** [comment]
This just came up on the forum again https://forum.qiime2.org/t/cutadapt-demultiplexing-with-mixed-primers/15260/2
