### ISSUE TITLE
Add Log Ouput

### ISSUE THREAD

**Issue by michoug** [qiime2/q2-cutadapt#13]
Hi
Is it possible to add an option to print/save the log of the software?
I just want to be sure that all the reads contained the primers that I want to remove.
This information was shown in the "original" cutadapt software.
Best
Greg

**Comment by thermokarst** [comment]
Hi @michoug - can you please ask this question on the [QIIME 2 forum](https://forum.qiime2.org) - that is where we provide official support for the project. Thanks!
