### ISSUE TITLE
Expose --m (min output read length) parameter

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-cutadapt#17]
For now reads that don't pass this filter will have to be written to `/dev/null`, since we haven't squared away the nullable outputs situation brought up in https://github.com/qiime2/q2-cutadapt/issues/10. In the meantime, the methods can use a `Range` to enforce a minimum read length of 1, which will prevent `FastqGzFormat` validation issues.

---

This recently came up on the forum:
- [here](https://forum.qiime2.org/t/cutadapt-thinks-my-fastq-gz-files-arent-fastq-gz/3355)
- [here](https://forum.qiime2.org/t/plugin-error-from-cutadapt/3360/)

**Comment by edisagarcia** [comment]
Hi thermokarst,
Please can you explain the use of Range in the qiime cutadapt demuxed -paired command? (QIIME2 2018)
I also have the problem with the FastqGzFormat recognition.
Please HELP!!

**Comment by thermokarst** [comment]
Whoops! Forgot to implement this for `demux_single` and `demux_paired`. @Oddant1, you up for taking that on? You can take the work that was done in #28 and apply it to to two demux methods. If you're up for it, let's chat Tuesday or Wednesday. Thanks!

**Comment by Oddant1** [comment]
@thermokarst that sounds great, I'm looking over it right now.
