### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-cutadapt#18]
Just like with [q2-demux](https://github.com/qiime2/q2-demux/blob/master/q2_demux/_demux.py#L66-L97), it looks like we need to investigate filehandle accounting here, too. Unfortunately, it looks like the issue is originating within cutadapt or one of its related tools, xopen.

This recently [came up on the forum](https://forum.qiime2.org/t/plug-in-error-from-cutadat/3417).

**Comment by jakereps** [comment]
Found the culprit [here](https://github.com/marcelm/cutadapt/blob/1be48f1e146a2f900f08b9fdde2a7c3475e74395/src/cutadapt/filters.py#L235-L236). Same cause of the initial `q2-demux`issue - storing open file handles for later writing. Is this something worth opening on their end, or where should we go from here? Only thing possible from the `q2` side would be mini-batching the adapters in a loop calling `cutadapt`.

**Comment by thermokarst** [comment]
Thanks @jakereps --- what do you think, @ebolyen ?

**Comment by ebolyen** [comment]
It seems like the polite thing to do would be to offer to fix this upstream. If they aren't interested in a patch, then we can just batch stuff on our end.

**Comment by thermokarst** [comment]
@jakereps - want to take point on opening an issue (after checking for an existing one)? Would you be up for volunteering, too? This would be part of your q2-related work, BTW.

**Comment by jakereps** [comment]
Can do! Almost went straight to their issue tracker out of habit, but figured I’d check in first, haha.

**Comment by emilyjunkins** [comment]
Has this issue been fixed?  I am running 2018.6 and getting the same error (OSError 24). Should I just go ahead and update q2 for the fix?

**Comment by thermokarst** [comment]
Hey there @emilyjunkins  - no, it doesn't look like it has been fixed yet upstream (https://github.com/marcelm/cutadapt/issues/320). Stay tuned!

**Comment by ebolyen** [comment]
It might be worth fixing on the q2 side in the meanwhile. I would be happy to review a PR @emilyjunkins if you were interested (and this month is [Hacktoberfest](https://hacktoberfest.digitalocean.com/) so all the better!)

**Comment by thermokarst** [comment]
I started implementing chunking on the plugin side, but parameterizing a batch size of n samples to demux at a time. One issue though is that processing in batches throws off the "untrimmed" output, since all the samples not present in a given batch are going to be listed as untrimmed. Some options come to mind:

- drop the "untrimmed" output, it is of limited utility anyway
- keep the untrimmed, don't do anything to "clean up" the leaked samples
- attempt to dedupe the untrimmed. I think this would require tracking each individual batch, then somehow intersecting the demux reads and the untrimmed reads. Sounds like a pain.

Thoughts?

**Comment by ebolyen** [comment]
Why does that happen? I don't entirely follow why the untrimmed (which means not-demuxed right?) would be different.

**Comment by thermokarst** [comment]
Demuxing samples A, B, C, D, E (let's assume every read in the muxed reads maps to a sample)

Chunk size 5: unmatched is empty
Chunk size 4: first, demux A, B, C, D --- unmatched has all reads from E. Next, demux D, this round has no unmatched reads.
Chunk size 3: first, demux A, B, C --- unmatched has all reads from D and E. Next, demux D & E, this round has no unmatched reads.
ad nauseum.

I suppose instead of always demuxing the _input_ muxed seqs, you could have the non-first demux rounds use the unmatched reads as their input. Thoughts?

**Comment by thermokarst** [comment]
I think I will go with the option of using the unmatched from round n as the input from round n+1, rather than always reusing the initial reads.

**Comment by ebolyen** [comment]
Ok I understand now, thank you! So because we are self-batching, we're calling cutadapt with fewer than the total number of samples, as otherwise it would open a FD for each sample, hence the problem. So it's always working with incomplete information.

Passing the unmatched as one more input sounds good to me!
