### ISSUE TITLE
Include quality trimming in the q2-cutadapt plugin?

### ISSUE THREAD

**Issue by JCSzamosi** [qiime2/q2-cutadapt#34]
**Improvement Description**
I don't know if this has already been discussed, but I wonder if people would be open to including quality trimming in the cutadapt plugin.

**Current Behavior**
Right now the q2-cutadapt plugin only trims adapters, and quality trimming needs to be done using the q2-quality-filter plugin.

**Proposed Behavior**
It would be nice if the option was available to take advantage of cutadapt's quality-trimming functionality in this plugin. I think it would have a few advantages:
1. cutadapt's quality trimming algorithm is more sophisticated than the one implemented in q2-quality-filter and, IME, produces cleaner sequences with less need for trying various parameter values
2. Given that every time a qiime2 plugin is called, the user needs to wait for the objects to get unzipped and rezipped, reducing the number of plugins required to perform conceptually-grouped tasks seems like a good thing (within reason).
3. Omitting this functionality feels like it hobbles the plugin compared to running cutadapt on its own, and is therefore a barrier to entry for more experienced users who are accustomed to using cutadapt or similar tools already.

I've never contributed to an open-source project before, but I could probably fork this repo and add the functionality if that's desirable (or whatever your process is).

**Comment by ebolyen** [comment]
Hey @JCSzamosi! Sorry for the very slow response on our part. I think that sounds like a great idea, and I would be happy to help you along in that process.

The first step would be to fork and clone the repo, then you would follow these instructions:
https://dev.qiime2.org/latest/quickstart/

In particular, the `make dev` is important to ensure that your development environment is using the source code you are editing, and not a prior dev build.

Let me know if you have further questions (the Forum's Dev category would also be a good place for general getting started questions)!

**Comment by JCSzamosi** [comment]
Thanks! My apologies, I somehow missed this message. I'll get going on it asap.

**Comment by colinvwood** [comment]
Feel free to reopen if desired.
