### ISSUE TITLE
When called from a shell script, qiime2 is calling the system version of cutadapt, not the qiime version.

### ISSUE THREAD

**Issue by JCSzamosi** [qiime2/q2-cutadapt#35]
**Bug Description**
When I run the q2-cutadapt plugin directly on the command line, it behaves fine, but when I call it from inside a script it calls the system version of cutadapt instead of the qiime2 version. 

It is not a case of the qiime2 environment failing to activate inside the script. If that were the case, the qiime2 commands wouldn't work at all.

I have attached a screenshot, the script in question, and qiime2's log file pertaining to the error.

[trim_test.sh.txt](https://github.com/qiime2/qiime2/files/3453622/trim_test.sh.txt)

![Screenshot.png](https://user-images.githubusercontent.com/4465403/62242743-d40d5800-b3a9-11e9-81d5-7974a5a85cef.png)

In particular, I draw your attention to line 7 in the log file, where the traceback shows that it's using my system version of cutadapt:

[qiime2-q2cli-err-eu6loi4f.log](https://github.com/qiime2/qiime2/files/3453631/qiime2-q2cli-err-eu6loi4f.log)

**Comment by thermokarst** [comment]
I suspect that conda is not setting up its environment correctly from within your script (one way to check is to compare the results of the `env` command in a few different places in this pipeline). Sounds like something is going wrong with `$PATH`, specifically (if I had to guess). Perhaps you could look into best practices for this on the conda docs?

**Comment by thermokarst** [comment]
Oh, looking at your script, I think one reason for this issue is your shebang:

```bash
#!/bin/bash
```

If you update to

```bash
#!/usr/bin/env bash
```

I suspect this will rectify the problem, because this will ensure your `$PATH` is translated correctly (I hope! :crossed_fingers:)

**Comment by JCSzamosi** [comment]
`#!/usr/bin/env bash` did not solve it, unfortunately. I'll poke around my path and look at the conda docs. 

It might be worth considering adding some documentation of this to the qiime2 docs if this is something that's likely to come up when using shell scripts.

**Comment by thermokarst** [comment]
>  if this is something that's likely to come up when using shell scripts.

Generally it isn't an issue, I suspect something in your computation environment might be complicating this. Thanks!

**Comment by JCSzamosi** [comment]
Seems likely. Switching from `conda activate` to `source activate` in scripts solved it for me. Thanks again!
