### ISSUE TITLE
Plugin error from cutadapt:

### ISSUE THREAD

**Issue by SerenaGalie** [qiime2/q2-cutadapt#37]
Hi all,

I have an error with cudadapt plugin. I am trying to demultiplex a file which contain single end sequences of both forward and reverse reads. I have just tried once this demultiplexing script with a similar file and it worked, but now that I used another file with the same characteristics it didn't. Could it may be related with some wrong sample, which has no forward reads? 

Here i live you the error message I get:

  Command '['cutadapt', '--front', 'file:/scratch-local/mbloemen/tmpvu_nizlr', '--error-rate', '0.0', '-o', '/scratch-local/mbloemen/q2-CasavaOneEightSingleLanePerSampleDirFmt-s8ii_4q0/{name}.1.fastq.gz', '--untrimmed-output', '/scratch-local/mbloemen/q2-MultiplexedSingleEndBarcodeInSequenceDirFmt-d72v4q_v/forward.fastq.gz', '/scratch-local/mbloemen/qiime2-archive-23n9wvxj/2cc054c9-525f-4181-951e-9ea0e0c5b3c6/data/forward.fastq.gz']' returned non-zero exit status -9

Thank you very much in advance,

Serena

**Comment by thermokarst** [comment]
Hi @SerenaGalie! Please post this question to the QIIME 2 Forum (https://forum.qiime2.org), that is where we provide user support. Thanks!
