### ISSUE TITLE
add support for cut-length parameters to trim-* actions

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-cutadapt#62]
Forum x-ref: https://forum.qiime2.org/t/is-it-possible-to-truncate-trim-right-3-end-without-filtering-by-length/30983/9

**Comment by lizgehret** [comment]
similar functionality has already been implemented in cutadapt: https://github.com/qiime2/q2-cutadapt/pull/57

**Comment by gregcaporaso** [comment]
Thanks @lizgehret, I forgot about that one. It looks like that is only on the `demux-` actions. For this user's use case it would need to be added to the `trim-` actions as well.
